### ISSUE TITLE
Some info about the engine

### ISSUE THREAD

**Issue by Cosetto** [TesterTesterov/gscScriptCompAndDecompiler#4]
The dev by mistake remained the source code controls the font, text box in English release of [this game](https://vndb.org/v23000)
![image](https://github.com/TesterTesterov/gscScriptCompAndDecompiler/assets/81801486/af6ba518-721b-4070-bc3d-57c550d21e2b)
And I used it to trace and find out the compiled file is 0500.gsc. Then I downloaded [Ever Maiden](https://vndb.org/v31427) to test it out...
![image](https://github.com/TesterTesterov/gscScriptCompAndDecompiler/assets/81801486/a46dd3ea-8c1c-4e45-b643-43b49f13adc7)
Yup, it seems like I hit the jackpot
![image](https://github.com/TesterTesterov/gscScriptCompAndDecompiler/assets/81801486/b39f7e82-339b-4e54-bba6-5cf1490d3b11)

**Comment by Cosetto** [comment]
It would be nice if you can change this to batch decompile files

**Comment by TesterTesterov** [comment]
@Cosetto, are you sure that it is *that* engine? It is possible that it could be just close script, but not quite it.

**Comment by Cosetto** [comment]
@TesterTesterov Yes, codeX RScript. I decompile the script with this tool
Another thing I found about the engine:
0500.gsc controls the font size and line spacing in the first script, the first script controls the font size and line spacing in the 2nd script, and so on.
